version: "2.20.3"
services:
  myapp:
    # image: server-mock
    # ports:
    #   - "8080:8080"
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo-docker
  mongo-docker:
    image: mongo
    ports:
      - "27017:27017"